name: Generate Data Index

on:
  push:
    branches: [main]
    paths:
      - "data/**"
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch all history for commit analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate Index
        run: |
          node scripts/generate-index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add datapaw-index.json
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: Update data index [skip ci]"
          git push
