name: Generate Data Index

on:
  push:
    branches: [main]
    paths:
      - "data/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch all history for commit analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate Index
        run: |
          # Use personal token if available, otherwise fall back to built-in token
          if [ -n "${{ secrets.PERSONAL_GITHUB_TOKEN }}" ]; then
            echo "Using personal GitHub token"
            export GITHUB_TOKEN="${{ secrets.PERSONAL_GITHUB_TOKEN }}"
          else
            echo "Using built-in GitHub token"
            export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          fi

          # Set default author information
          export DEFAULT_AUTHOR_NAME="${{ secrets.DEFAULT_AUTHOR_NAME || 'Datapaw' }}"
          export DEFAULT_AUTHOR_GITHUB="${{ secrets.DEFAULT_AUTHOR_GITHUB || 'afnizarnur' }}"
          export DEFAULT_AUTHOR_AVATAR="${{ secrets.DEFAULT_AUTHOR_AVATAR || 'https://github.com/afnizarnur.png' }}"

          node scripts/generate-index.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.json
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: Update data index [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
